- name: Download repo
  git:
    repo: https://github.com/jyepesr1/movie-analyst-api
    dest: "{{ APP_PATH }}"
    version: dev

- name: Install node.js dependencies
  yarn:
    path: "{{ APP_PATH }}"

- name: Set secrets file
  template:
    src: .env.j2
    dest: "{{ APP_PATH }}/.env"
    mode: '0600'

- name: Delete old app process
  command: ./node_modules/.bin/pm2 delete server
  args:
    chdir: "{{ APP_PATH }}"
  ignore_errors: true
  become_user: "{{ USER }}"
  environment:
    HOME: "/home/{{ USER }}"

- name: Execute app
  command: yarn start
  args:
    chdir: "{{ APP_PATH }}"
  become_user: "{{ USER }}"
  environment:
    HOME: "/home/{{ USER }}"