- name: Update all packages to latest
  yum: 
    name: '*'
    state: latest
    lock_timeout: 180

- name: Install basic tools
  yum:
    name:
      - git
      - gcc-c++
      - make
      - python3
    state: latest
    lock_timeout: 180
