- name: Update all packages to latest
  yum: 
    name: '*'
    state: latest
    lock_timeout: 180

- name: Install basic tools
  yum:
    name:
      - git
      - gcc-c++
      - make
      - python3
    state: latest
    lock_timeout: 180

- name: Add cron to execute ansible every reboot
  cron:
    name: "Execute ansible when instance is rebooted"
    special_time: reboot
    job: "cd /usr/ansible && ansible-playbook --vault-id @get_pass.sh --connection=local -i 127.0.0.1, ./playbooks/{{ ansible_play_name }}.yml"
    cron_file: ansible_bootstrap
    user: ec2-user
